// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApXe6eGbVQZGn_tyq_dI3wIhJ_tM09Hvw',
    appId: '1:246928857627:web:3731d46e45b0828c0176be',
    messagingSenderId: '246928857627',
    projectId: 'fir-storge-de5cb',
    authDomain: 'fir-storge-de5cb.firebaseapp.com',
    databaseURL: 'https://fir-storge-de5cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-storge-de5cb.appspot.com',
    measurementId: 'G-YPJPKVCPV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuzn4d0grm4Blx-usQLMrsQU-IbFkZ33w',
    appId: '1:246928857627:android:510751a3c7972d5f0176be',
    messagingSenderId: '246928857627',
    projectId: 'fir-storge-de5cb',
    databaseURL: 'https://fir-storge-de5cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-storge-de5cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB25OaFFir5IWZDY505qMckCjuJhYFIlzA',
    appId: '1:246928857627:ios:0ab1ee3d1449ab910176be',
    messagingSenderId: '246928857627',
    projectId: 'fir-storge-de5cb',
    databaseURL: 'https://fir-storge-de5cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-storge-de5cb.appspot.com',
    androidClientId: '246928857627-a9g2f34b3c3klr20fapbd8vaet54nj3s.apps.googleusercontent.com',
    iosClientId: '246928857627-hnig9qjj6kilqecc2vjp1p5rmeg9ms8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
