// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbohzibQ1QDz1OBl2vYwtTDftDlrdC_WI',
    appId: '1:645151843994:web:137956079a0ba3b2ab2123',
    messagingSenderId: '645151843994',
    projectId: 'fir-crud-ffe3b',
    authDomain: 'fir-crud-ffe3b.firebaseapp.com',
    databaseURL: 'https://fir-crud-ffe3b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-crud-ffe3b.appspot.com',
    measurementId: 'G-BCXC3Q4GK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs1yMGII8UYdtLCk6HTpWZ3anQ9tN2Zrg',
    appId: '1:645151843994:android:946df81795e62f2aab2123',
    messagingSenderId: '645151843994',
    projectId: 'fir-crud-ffe3b',
    databaseURL: 'https://fir-crud-ffe3b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-crud-ffe3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9szQESktcdaz_e2Ts8sP75PLzbi8QvLM',
    appId: '1:645151843994:ios:2097f6dc690124f9ab2123',
    messagingSenderId: '645151843994',
    projectId: 'fir-crud-ffe3b',
    databaseURL: 'https://fir-crud-ffe3b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-crud-ffe3b.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
