// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbS8Qfx7Dbxvdi5wKcxGojxc9EsFlgyzg',
    appId: '1:135986466309:web:12d65e2b877edffb4e566c',
    messagingSenderId: '135986466309',
    projectId: 'e-commerce-app-e88ba',
    authDomain: 'e-commerce-app-e88ba.firebaseapp.com',
    storageBucket: 'e-commerce-app-e88ba.firebasestorage.app',
    measurementId: 'G-XD6NK3E31Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnLvrAg-lPVeOBOPVyBTjknkuBmb2AR38',
    appId: '1:135986466309:android:1a0a1cc0388b88ca4e566c',
    messagingSenderId: '135986466309',
    projectId: 'e-commerce-app-e88ba',
    storageBucket: 'e-commerce-app-e88ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-wNMudBInpLd0bxn9LNM_OWt8hV4loCI',
    appId: '1:135986466309:ios:13173d8ae88daaf14e566c',
    messagingSenderId: '135986466309',
    projectId: 'e-commerce-app-e88ba',
    storageBucket: 'e-commerce-app-e88ba.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
